import React, { useState } from 'react';
import { FilterState } from '../types';
import { getGeminiInsight } from '../services/geminiService';
import { Sparkles, Loader2 } from 'lucide-react';

interface Props {
  filters: FilterState;
}

const GeminiInsight: React.FC<Props> = ({ filters }) => {
  const [insight, setInsight] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleAsk = async () => {
    setLoading(true);
    const text = await getGeminiInsight(filters);
    setInsight(text);
    setLoading(false);
  };

  if (!process.env.API_KEY) return null; // Hide if no key

  return (
    <div className="mt-8">
      {!insight ? (
        <button 
          onClick={handleAsk}
          disabled={loading}
          className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-violet-600 to-indigo-600 text-white p-3 rounded-xl font-medium hover:opacity-90 transition-all shadow-lg hover:shadow-indigo-500/20"
        >
          {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
          {loading ? "Consulting the Oracle..." : "Get AI Reality Check"}
        </button>
      ) : (
        <div className="bg-gradient-to-br from-violet-50 to-indigo-50 border border-indigo-100 p-4 rounded-xl relative">
          <button 
            onClick={() => setInsight(null)} 
            className="absolute top-2 right-2 text-indigo-300 hover:text-indigo-500"
          >
            ×
          </button>
          <div className="flex items-start gap-3">
             <div className="bg-indigo-100 p-2 rounded-lg text-indigo-600">
                <Sparkles className="w-5 h-5" />
             </div>
             <div>
               <p className="text-indigo-900 text-sm font-medium leading-relaxed">
                 "{insight}"
               </p>
               <p className="text-indigo-400 text-xs mt-2">Generated by Gemini</p>
             </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default GeminiInsight;